format = """
$username\
$hostname\
$directory\
$git_branch\
$git_state\
$git_status\
$cmd_duration\
$line_break\
$python\
$character"""

[directory]
style = "#82aaff"  # Tokyo Night Moon blue

[character]
success_symbol = "[❯](#c099ff)"  # Tokyo Night Moon purple
error_symbol = "[❯](#ff757f)"     # Tokyo Night Moon red
vimcmd_symbol = "[❮](#c3e88d)"    # Tokyo Night Moon green

[git_branch]
format = "[$branch]($style)"
style = "#c099ff"  # Tokyo Night Moon purple

[git_status]
format = "[[(*$conflicted$untracked$modified$staged$renamed$deleted)](218) ($ahead_behind$stashed)]($style)"
style = "#86e1fc"  # Tokyo Night Moon cyan
conflicted = "​"
untracked = "​"
modified = "​"
staged = "​"
renamed = "​"
deleted = "​"
stashed = "≡"

[git_state]
format = '\([$state( $progress_current/$progress_total)]($style)\) '
style = "#636da6"  # Tokyo Night Moon muted purple

[cmd_duration]
format = "[$duration]($style) "
style = "#ffc777"  # Tokyo Night Moon yellow

[python]
format = "[$virtualenv]($style) "
style = "#636da6"  # Tokyo Night Moon muted purple
